import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./(marketing)/_components/navbar"; 
import "./globals.css";
import { ConvexClientProvider } from "@/components/providers/convex_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coauthor",
  // description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`h-screen ${inter.className}`}>
      <ConvexClientProvider>
                  {children}
              </ConvexClientProvider>
      </body>
    </html>
    // <div className="h-full dark:bg-[#1F1F1F]">
    //         <Navbar />
    //           <main className="h-full pt-40 pb-40 dark:bg-[#1F1F1F]">
            
    //     </div>
  );
}
